### ISSUE TITLE
need help getting chef-client to run inside container

### ISSUE THREAD

**Issue by glenndavy** [Atalanta/cucumber-chef#67]
wondering if you can help me make sense of this error. I 've used the basic provisioning steps, and the attempt to run the chef-client in the container is faling:

```
    * the chef-client has been run on "xyz"    # cucumber-chef-2.0.1.pre/lib/cucumber/chef/steps/provision_steps.rb:58
      command_run_remote(/usr/bin/chef-client -j /etc/chef/attributes.json -N xyz ) failed (65280) (RuntimeError)
      ./xyz/xyz.feature:14:in `* the chef-client has been run on "xyz"'
```
- I've included and uploaded the chef-client recipe
- the node xyz has chef-client::service as recipe in its run list. 

Anything else I might have over looked?

**Comment by zpatten** [comment]
The 65280 RunetimeError generally means the remote command failed because either it couldn't connect via SSH to run the command or the chef-client didn't get pushed into your master LXC image.  I would suggest connecting into your container via the `cucumber-chef` tool and manually running the chef-client command.

If memory serves correctly; I would usually just destroy the container and let it get recreated if all my test runs where returning this error while running against said container.

**Comment by glenndavy** [comment]
Hey zpatten
Firstly, thanks for the super responsiveness replying. So for sure its an inability to ssh in. Destroying containers didn't help, so I took the easy way out and just tore down the test lab and started over. I still had an issue, but this time I was able to ssh in using the IP.  For now, adding the node name (xyz in the example  above) the the hosts file gets me out of trouble, I guess the  dynamic dns isn't updating when dhcp allcoates the ip? I'll check that out in a bit, If i learn anything there, or hit probs I'll add another issue, but for now /etc/hosts lets me move forward.
Thanks again for the lead.
